# Generated by Django 2.1.4 on 2018-12-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('finished', models.BooleanField()),
                ('last_update', models.DateField()),
                ('num', models.IntegerField(unique=True)),
                ('introduction', models.TextField(max_length=2000)),
            ],
        ),
    ]
